export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT_START = "LOGOUT_START"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const SET_USER = "SET_USER"

export const LOGIN_WITH_GOOGLE_START = "LOGIN_WITH_GOOGLE_START"
export const LOGIN_WITH_GOOGLE_SUCCESS = "LOGIN_WITH_GOOGLE_SUCCESS"
export const LOGIN_WITH_GOOGLE_FAIL = "LOGIN_WITH_GOOGLE_FAIL"


export const LOGIN_NUMBER_START = "LOGIN_NUMBER_START"
export const LOGIN_NUMBER_SUCCESS = "LOGIN_NUMBER_SUCCESS"
export const LOGIN_NUMBER_FAIL = "LOGIN_NUMBER_FAIL"

